>Human_Kif11|NP_004514.2
MASQPNSSAKKKEEKGKNIQVVVRCRPFNLAERKASAHSIVECDPVRKEVSVRTGGLADK
SSRKTYTFDMVFGASTKQIDVYRSVVCPILDEVIMGYNCTIFAYGQTGTGKTFTMEGERS
PNEEYTWEEDPLAGIIPRTLHQIFEKL-TDNGTEFSVKVSLLEIYNEELFDLLNPSSDVS
ERLQMFDDPRNKRGVIIKGLEEITVHNKDEVYQILEKGAAKRTTAATLMNAYSSRSHSVF
SVTIHMKETTIDGEELVKIGKLNLVDLAGSENIGRSGAVDKRAREAGNINQSLLTLGRVI
TALVERTPHVPYRESKLTRILQDSLGGRTRTSIIATISPASLNLEETLSTLEYAHRAKNI
LNKPEVNQKLTKKALIKEYTEEIERLKRDLAAAREKNGVYISEENFRVMSGKLTVQEEQI
VELIEKIGAVEEELNRVTELFMDNKNELDQCKSDLQNKTQELETTQKHLQETKLQLVKEE
YITSALESTEEKLHDAASKLLNTVEETTKDVSGLHSKLDRKKAVDQHNAEAQDIFGKNLN
SLFNNMEELIKDGSSKQKAMLEVHKTLFGNLLSSSVSALDTITTVALGSLTSIPENVSTH
VSQIFNMILKEQSLAAESKTVLQELINVLKTDLLSSLEMILSPTVVSILKINSQLKHIFK
TSLTVADKIEDQKKELDGFLSILCNNLHELQENTICSLVESQKQCGNLTEDLKTIKQTHS
QELCKLMNLWTERFCALEEKCENIQKPLSSVQENIQQKSKDIVNKMTFHSQKFCADSDGF
SQELRNFNQEGTKLVEESVKHSDKLNGNLEKISQETEQRCESLNTRTVYFSEQWVSSLNE
REQELHNLLEVVSQCCEASSSDITEKSDGRKAAHEKQHNIFLDQMTIDEDKLIAQNLELN
ETIKIGLTKLNCFLEQDLKLDIPTGTTPQRKSYLYPSTLVRTEPREHLLDQLKRKQPELL
MMLNCSENNKEETIPDVDVEEAVLGQYTEEPLSQEPSVDAGVDCSSIGGVPFFQHKKSHG
KDKENRGINTLERSKVEETTEHLVTKSRLPLRAQINL
>Caenorhabditis_Kif|D67861.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------F
MVNVVIRENTTTGEELVKQGKLNLVDLAGSENIGRSGAQGNRAKQAXSIIHSVXKMPXVI
RLLTTNXQHIPYRESKLTRLLQDSLGGSTLTSVIATLSPSXSNFEESQSTLVYAMRAA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Haemonchus_Kif|VDO56086.1
---------------------------MSDMERADNATSVVKVEEKKMMVTCK-------
-SKTFSAFDKVYGPSTTQERIYAEMVSPQVDRVLAGYNCTLFAYGQTGTGKTYTMEGGRG
ERSSY--KDDPTTGIIPRAVEHIFEELEKSH------VCDTLSIHPIQRPNQLSGIN---
-----FRRPVKKGIPI--NCCELPVKNRSEVYALLKRGAEKRTTAATLMNMNSSRSHSIF
IVSVVIRENTPNGEELVKQGKLNLVDLAGSEHIGRSGAEGKRAKEAGNINQSLLTLGRVI
TALTTSAPHVPYRESKLTRLLQDSLGGSTITSIIATLSPASSNYEESISTLEYAARAKSI
RNHPECNQKLSRKALLKEYNEEIEKLRRDLRTAREKNGIFLSQESY--------------
------------------------------------------------------------
-----------------------IAEKTEQLQELEGQLDAAIGKLQKFIEDQEMMDEQYR
ELYHRNKRL---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EAKLRQRVEELDDTKKVCHKKPTIFQARITVFDQQLDLEDWWAKEENLSQLIAQNKQVV
VAARSKVQTWLLFFDFSMITTVF-------------------------------------
------------------------------------------------------------
-------------------------------------
>Angiostrongylus_Kif|VDM55674.1
------MSSMSKKQDKINVRVAVRVRPMSDAERADNATSIVKVEEKKMTVTCK-------
--------SKVYGTSANQERIYKEMVSPQVERVLAGYNCT---YGQTGTGKTYTMEGGCA
SDASY--KNDPTTGIIPRAVEHIFEELEKSNTEEYSIRVSYLELYNEELYDLLAPTSDDR
ERLRIFDDPSKKGMVVVSGAEELPVRNRFEVYNLLKRGADRRVTAATLMNMNSSRSHSIF
TVSVVLRENTQNGEELVKQGKLNLVDLAGSEHIGRSGAEGKRAKEAGNINQSLLTLGRVI
TALTTSAPHVPYRESKLTRLLQDSLGGSTITSIIATLSPASTNYEESVSTLEYAARAKSI
RNHPECNQTLTRKALLKEYNEEIEKLRRDLRSAREKNGIFLSQESY--------------
------------------------------------------------------------
---------------------------------------TG-------------MENEIA
TKTEQLREL---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EGQLDAAIKKLQKVC--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Ancylostoma_Kif|KIH54759.1
------------------------------------------------------------
------------------------MVSPQVDRVLAGYNCTLFAYGQTGTGKTYTMEGGSG
EHNSY--KEDPTTGIIPRAVEHIFEELEKSNTEEYSVRVSYLELYNEELYDLLAPTSDDR
ERLRIFDDPLKKGMVVISGVEEIPVKDRAEVYRLLKRGAEKRTTAATLMNMHSSRSHSIF
TVSVVIRENTPNGEELVKQGKLNLVDLAGSEHIGRSGAEGKRAKEAGNINQSLLTLGRVI
TALTTSAPHVPYRESKLTRLLQDSLGGATITSIIATLSPASTNYEETISTLEYAARAKSI
KNHPECNQKLSRKALLKESNEEIERLRRDLRTAREKNGIFLSTESY--------------
------------------------------------------------------------
---------------------------------------E--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Heligmosomoides_Kif|VDP18331.1
---------------------------MNEAEKADNSISVVKVEEKKMTVTCK-------
-SKSFSAFDKVYGPATTQERIYKEMVSPQVERVLAGYNCTLFAYGQTGTGKTYTMEGGSS
DRSSY--KHDPSTGIIPRAVDGMGSNL----------FFSYLELYNEELYDLLAPTVEDR
ERLRIFDDPSKKGMVVISGAEEIPVRDRSEVYSLLKRGAEKRTTAATLMNMHSSRSHSIF
SVSVVIRENTPNGEELVKQGKLNLVDLAGSEHIGRSGAEGKRAKEAGNINQSLLTLGRVI
TSLTTSAPHVPYRESKLTRLLQDSLGGSTITSIIATLSPASCNYEESISTLEYAARAKSI
RNHPECNQKLSRKALLKEYNEEIEKLRRDLRTAREKNGIFLSQESY--------------
------------------------------------------------------------
---------------------------------------DGLWRKFQFIEDQELMDEQYR
ELYHRNKRL---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EAKLRQRVDELDDTKKV------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
